app/assets/javascripts/cascade/level/flickr-picasa.js, app/views/widgets/right_column/_picasa_gallery.html
Trello card: https://trello.com/c/fnARAJmi/.
I'll need help deploying to dev and then production.
=> [DEFECT] https causes pages with flickr/picasa feeds to not show thumbnails on www.

app/assets/stylesheets/widgets/_ad_landing_page/masthead.scss, app/assets/stylesheets/widgets/_ad_landing_page/messaging.scss, app/assets/stylesheets/widgets/_ad_landing_page/sponsor_bar.scss, app/views/widgets/ad_landing_page/_masthead.html, app/views/widgets/ad_landing_page/_messaging_only.html
https://trello.com/c/ax1LuaOQ/21-update-landing-pages-on-cascade-to-reflect-style-changes-made-on-the-standalone-pages
=> Landing page style refinement

README.md
https://trello.com/c/3Zo4BinB/72-support-brei-acceptance-testing-for-cascade
Only changes README.
Please also review the following new Knowledge Base pages, some of which replace parts of the README:
- [Cascade Testing Guidelines](https://kb-smc.chapman.edu/?p=1876)
- [Cascade Acceptance Testing](https://kb-smc.chapman.edu/?p=1860)
- [Deploying Assets from Cascade Assets to Cascade](https://kb-smc.chapman.edu/?p=1894)
- [Deploying HTML from Cascade Assets to Cascade](https://kb-smc.chapman.edu/?p=1887)
Revisions and suggestions are welcome.
=> New acceptance testing guidelines

app/assets/stylesheets/base/defaults.scss, app/assets/stylesheets/base/mixins.scss, app/assets/stylesheets/components/callout.scss, app/assets/stylesheets/layout_old/footer.scss
Title font changes to Futura for h1/h2 headers.
=> Site-Wide h1-h2 title font changes

app/assets/stylesheets/layout_old/footer.scss
- Trello Card: https://trello.com/c/K3q9aROR/
- Issue #89
=> [DEFECT] The wave tool creates a false-negative for the Chapman website, resulting on many ADA violations per page.

app/assets/javascripts/cascade/new-home.js, app/views/widgets/home_page/_hero_panel.html
https://trello.com/c/gpJ3fAfM/120-urgent-watch-video-button-on-www-home-page-in-production-is-not-working
Fixes Issue #93.
=> [URGENT] Watch Video button on WWW home page in production is not working.

app/assets/javascripts/cascade/level/flickr-picasa.js, app/views/widgets/right_column/_picasa_gallery.html
https://trello.com/c/R9oC7wUj/
=> [DEFECT] In Cascade Asset code, Flickr widget is making AJAX calls even on pages where not displayed.

app/assets/stylesheets/widgets/home_page/undergraduate_admission.scss
Trello card: https://trello.com/c/irVUpYgd/
Fixes Issue #140.
=> As an IE user I can't see the UG stats.

app/assets/stylesheets/widgets/chapman_events_feed.scss, lib/assets/javascripts/chapman_events_feed.js
https://trello.com/c/XgMvtmC4/318-as-a-www-site-user-i-would-like-to-see-the-updated-events-chapman-widget
=> updating events feed formatting

app/assets/javascripts/cascade/level/faculty.js, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml
by request of Crean College, add new dept codes to our javascript that filters school/depts for faculty directory pages so includes CSD and ATPE which are some of their graduate programs. And, convert Kinesiology from using HSCI to HSK dept code since all those faculty fall under that new code in PeopleSoft now
=> Fix Crean College dept filters in faculty directory

app/assets/javascripts/cascade/level/faculty.js, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml
update faculty.js for Crean College for filters used to produce school/dept faculty directory pages:
replace HSCI with HSK for dept code to filter for Kinesiology dept
add CSD and ATPE for grad programs
also change the code used in dept dropdown on main faculty search screen so Kinesiology uses HSK not HSCI
=> modify faculty directory filters for Crean College

app/data_definitions/from_cascade/one_column.xml
Trello Card: https://trello.com/c/qYoqdsKG/
=> As a Brochure Page Masthead user, I would like to be able to align the image to the top, center and bottom.

app/assets/stylesheets/base/colors.scss, app/assets/stylesheets/base/mixins.scss, app/assets/stylesheets/components/section_message.scss, app/assets/stylesheets/widgets/hero/side_panel.scss
Minor font style changes to match design comps.
=> One column widgets style changes

app/assets/stylesheets/base/mixins.scss
Additional style change I forgot in my previous PR.
=> Increased section title font size to match comp.

app/assets/javascripts/omni-nav.js, app/assets/stylesheets/omni_nav/modules/omni-nav.scss, app/views/widgets/shared/_omninav.html
https://trello.com/c/84FugV7d/350-defect-on-www-site-search-results-block-doesn-t-behave-nicely
=> [DEFECT] On www site, search results block doesn't behave nicely.

app/assets/stylesheets/regions/mastheads/boxes-masthead.scss
Story: https://trello.com/c/Ku2WIatw/
1 - Red box caption transition made faster
2 - Copy below title now appears immediately on hover
3 - Button now appears immediately on hover with some delay after the copy
=> Masthead box transition fix

app/assets/stylesheets/layout_old/form.scss, app/views/layouts/2_column.html.erb, app/views/layouts/3_column.html.erb, app/views/widgets/shared/_footer.html, app/views/widgets/shared/_head.html, app/views/widgets/shared/_header.html
changed some of static html for global nav bar so in sync with production, but these files only for localhost testing not the live site. Made minor edits to forms.scss and modified indenting while there
=> Static navigation bar updates

app/assets/stylesheets/components/icomoon.scss, app/assets/stylesheets/components/main_navigation.scss, app/assets/stylesheets/components/sub-nav-links.scss, app/assets/stylesheets/omni_nav/modules/off-canvas-nav.scss, app/views/widgets/shared/_header.html, app/views/widgets/shared/_omninav.html
Updated icons on Global and Off-Canvas Nav.
=> Global nav off canvas icon update

app/assets/stylesheets/widgets/primary_column/collapsibles.scss
- Trello Card: https://trello.com/c/zF1Vhk66
- Issue #205
=> On WWW site mobile, the collapsable region plus/minus button does not work to close the region.

app/assets/stylesheets/widgets/single_column/messaging.scss, app/views/1_column/law_theme.html.erb, app/views/dashboard/index.html.erb, app/views/widgets/single_column/_messaging_2_column_video_dark_bg.html
Trello Card: https://trello.com/c/mbvHybtr
Issue #207
=> On the WWW 1-column template, hyperlinks on the darker background gray color are red and it seems to have contrast issues.

app/assets/stylesheets/regions/mastheads/branded-masthead.scss, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml, app/views/_cascade/formats/level/_masthead.erb
- Trello Card: https://trello.com/c/EL4thcb6
=> As a WWW user, I would like to be able to add a caption to the branded masthead.

app/assets/stylesheets/widgets/home_page/graduate_admission.scss, app/views/widgets/home_page/_graduate_admission.html
https://trello.com/c/PDgsZsYX/412-as-a-prospective-graduate-student-id-like-to-be-able-to-request-info-directly-off-of-the-homepage
=> As a prospective graduate student, I'd like to be able to request info directly off of the homepage.

app/assets/javascripts/master.js, app/assets/javascripts/regions/mobile-nav.js, app/assets/stylesheets/components/breadcrumbs.scss, app/assets/stylesheets/layout_old/footer.scss, app/assets/stylesheets/master.scss, app/assets/stylesheets/regions/mobile-nav.scss, app/views/layouts/2_column.html.erb, app/views/layouts/3_column.html.erb, app/views/regions/_mobile_nav.html
Trello Card: https://trello.com/c/8RfLPlHF
=> As a WWW user on a mobile device less than 768px, I want to see responsive design changes implemented.

app/assets/stylesheets/components/callout.scss
https://trello.com/c/Yd5FflBm/443-defect-on-the-3-column-template-the-tablet-breakpoint-causes-the-site-to-bug-out-a-little-needs-fixin
=> [DEFECT] On the 3-column template, the tablet breakpoint causes the site to bug out a little.

app/assets/stylesheets/components/left-nav-ul.scss, app/assets/stylesheets/components/left-nav.scss, app/assets/stylesheets/layout_old/level-level.scss, app/assets/stylesheets/layout_old/primary-content.scss, app/assets/stylesheets/widgets/news-events-feed.scss
Trello Card: https://trello.com/c/j70XPtCo
Fixes issue #215.
=> On the 2-column template, the spacing between the left column and the primary content column is too big.

app/assets/stylesheets/widgets/_ad_landing_page/masthead.scss, app/assets/stylesheets/widgets/_ad_landing_page/messaging.scss
Story: https://trello.com/c/p3lbmj81
Fixed the padding for `ul` items and the positioning of the background image, but if @waidelacruz could double check to confirm that this is the position she had in mind, I'd appreciate it.
=> Fix landing template

app/assets/stylesheets/widgets/_ad_landing_page/masthead.scss, app/assets/stylesheets/widgets/_ad_landing_page/messaging.scss
This includes Shereef's changes for this story:
- https://trello.com/c/p3lbmj81/
=> Merges development into master.

app/assets/stylesheets/layout_old/footer.scss, app/views/widgets/shared/_footer.html
Edited _footer.html to sync with markup and link changes made in production Cascade for ADA but were lost in another recent update. Footer headings now H2 not H3 for ADA req. Footer links match live site. Social icon links contain text (though hidden with css) to pass ADA req for not having empty links.
=> Global footer updates

app/assets/javascripts/cascade/level/news-events.js, app/views/layouts/2_column.html.erb
- Trello Card: https://trello.com/c/aJ7QxbHh/
- Issue #221
=> News Event widget causing error on Schmid page.

.cascade-code/Chapman.edu/test-section/tatwell/query_api_spike/query_api.vtl, .gitignore
Trello Card: https://trello.com/c/InwKZ4w9
I believe we can use the Locator tool in conjunction with the $currentPage Cascade API object to build contextual nav components more efficiently.
Demo page with sample data:
- https://dev-www.chapman.edu/test-section/tatwell/query_api_spike/demo.html.aspx
Dev Cascade page (where you can check metrics):
- [Chapman.edu/test-section/tatwell/query_api_spike/demo.html](https://dev-cascade.chapman.edu/entity/open.act?id=96aa7446c0a814531e0ec9b7fcfd2951&type=page)
Feel free to raise question or suggest other trials.
=> [Spike] Replace dynamic menus index block with locator tool.

app/assets/javascripts/cascade/level/news-events.js, app/assets/stylesheets/themes/education.scss, app/views/widgets/shared/_omninav.html
can change blogs path now from /ces to /education; create new case in
News/Events javascript for Education not CES and change urls and text
files for caching in those cases
=> final changes for CES to Education

app/assets/javascripts/cascade/level/news-events.js, app/assets/stylesheets/themes/education.scss, app/views/widgets/shared/_omninav.html
minor changes so news widget will use new /education in url for blogs feed
=> final CES to Education changes for news widget and blogs link

.cascade-code/_cascade/formats/modular/widgets/Funnels_2up
Trello Card: https://trello.com/c/gt9YZaT3
Issue #249
=> As a user of the WWW site, I'd like the Funnel 2-up widget to be accessible.

.cascade-code/_cascade/formats/modular/widgets/Featured_News_Events_Left_Col, .cascade-code/_cascade/formats/modular/widgets/Featured_News_Events_Primary_Content, app/assets/javascripts/cascade/level/news-events.js, app/assets/stylesheets/layout_old/primary-content.scss, app/assets/stylesheets/widgets/news-events-feed.scss, app/views/widgets/left_column/_news_event_left_col.html, app/views/widgets/left_column/_news_events_1.html, app/views/widgets/primary_content/_featured_news_events_feed_1.html
Trello Card: https://trello.com/c/UVkFhbQx
Issue: #252
=> As a user of the WWW site I want the News/Events widget to be accessible.

.cascade-code/_cascade/formats/Homepage_Blog_Stories, .cascade-code/_cascade/formats/Homepage_CU_Family_section, .cascade-code/_config/blogs.vm, .cascade-code/_config/social.vm, README.md
Trello Story: https://trello.com/c/JlStwNlL
Issue #254.
=> Issue 254: Empty Links in Hompage Blogs Stories widget.

.cascade-code/_cascade/formats/modular/widgets/Funnels_2up
- Issue #258 
- Trello Card: https://trello.com/c/1aQgGCLu
=> On the 2-up funnel widget the supplementary links are no longer showing.

.cascade-code/Chapman.edu/_cascade/formats/Omni-Nav.vtl
Story: https://trello.com/c/QLLHbIvL
=> As a WWW user, when I am in the Careers section of the site, I want to see the Careers section listed in the off-canvas nav.

.cascade-code/Chapman.edu/_components/omni_nav_v2/omni_nav.vtl, app/assets/stylesheets/omni_nav/omni_nav_v2/off-canvas-nav.scss, app/views/omni_nav_v2/_off_canvas_nav.html.erb
Story: https://trello.com/c/NWW6Ttr8
Original pull request for implementing the dynamic OmniNav v2 in dev cascade: https://github.com/chapmanu/cascade-assets/pull/247
=> [DEFECT] New OmniNav OffCanvas menu does not include all expected links.

.cascade-code/Chapman.edu/_components/omni_nav_v2/omni_nav.vtl
Story: https://trello.com/c/SvloTLKb
The modified format can also be found/tested in Dev Cascade in `_components/omni_nav_v2/omni_nav.vtl`
=> Add Careers umbrella category to new OmniNav.

.cascade-code/Chapman.edu/_components/left_nav/left_nav.vtl, .cascade-code/Chapman.edu/_components/left_nav/left_nav_no_siblings.vtl
Trello story: https://trello.com/c/zwuWdHeF
Issue #265 
**Dev Cascade**
- Test formats: `_components/left_nav/`
- Live formats: `_cascade/formats/level/`
=> [URGENT] Left navigation format fixes - "_files" exclusion and root level fixes

.cascade-code/_cascade/formats/modular/widgets/Funnels_2up
Trello Card: https://trello.com/c/IE7KE3j2
Fixes Issue #267.
UAT page: https://dev-www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/web/primary-funnel-2up.aspx
=> Fix issues with links in 2-up funnel widget.

.cascade-code/Chapman.edu/_cascade/formats/home/Homepage Accessibility Statement section.vtl, app/assets/stylesheets/widgets/home_page/accessibility_statement.scss, app/data_definitions/from_cascade/home_page.xml, app/views/_cascade/blocks/html/_footer.html, app/views/_cascade/templates/home/Home Page v3.html, app/views/home_page/sample.html.erb, app/views/widgets/home_page/_accessibility_statement.html
deploying changes to CSS for new section on homepage for accessibility statement. Other changes are for localhost testing only.
=> new section on homepage for accessibility statement

.cascade-code/_cascade/formats/modular/widgets/Funnels_2up, app/views/widgets/primary_content/_funnel_2up_boxes_1.html
Story: https://trello.com/c/vkR163Ch
Updated the velocity so that a single link will surround both the image and the text.
=> Updates velocity so that a single link surrounds the image and text.

.cascade-code/Chapman.edu/_components/omni_nav_v2/omni_nav_v2.vtl, .cascade-code/Chapman.edu/_config/global_nav.vm, .cascade-code/Chapman.edu/_config/global_nav_law.vm
These came from the OmniNav v2 release story: https://trello.com/c/jQdhBj4O
Original PR: #228 
Does not require redeploying assets. The changes have been made to the velocity formats in Dev, will fix on production as well.
=> Minor OmniNav v2 link fixes

app/assets/javascripts/cascade/level/directory.js, app/assets/javascripts/cascade/level/faculty-law.js, app/assets/javascripts/cascade/level/faculty.js, app/assets/stylesheets/layout_old/faculty/main-faculty-search-results.scss, app/assets/stylesheets/layout_old/faculty/school-dept-faculty-search-results.scss
Faculty Directory changes for new Dean Title field, changes to Pres Fellow, and fix to ESI path for listing page filter. Applies to main listing page, school-filtered listing pages, and single profile page template as well
=> Faculty Directory Dean Title changes

app/assets/javascripts/omni-nav-v2.js
Trello Card: https://trello.com/c/h5jBaODO
Issue #295
=> OmniNav 2 conflict with Degrees and Programs.

app/assets/javascripts/cascade/level/flickr-picasa.js, static/_files/level/js/script_2013.js
changes to Flickr widget for alt text
=> changes to Flickr widget for alt text

.cascade-code/Chapman.edu/_cascade/blocks/html/search_results.html
Trello Card: https://trello.com/c/peFOAHOl
Issue #299
=> Search results page broken by deprecation of v1 of Google CSE API.

.cascade-code/Chapman.edu/_components/omni_nav_v2/omni_nav_v2.vtl, app/assets/javascripts/omni-nav-v2.js, app/assets/stylesheets/omni_nav/omni_nav_v2/omni-nav.scss, app/views/omni_nav_v2/omninav.html.erb
Story: https://trello.com/c/jAvZR52D
Issue #235 
JSFiddle: https://jsfiddle.net/2z85o02h/3/
=> [DEFECT] In OmniNav 2 on Firefox, issue with hover on search/user icons.

app/assets/javascripts/omni-nav-v2.js
Story: https://trello.com/c/5BNPbbsu
I tested in Chrome, Firefox, Safari and IE 11 on mobile and desktop views.
Next step is deploying to Dev Cascade.
=> Issue 305: OmniNav search function on Internet Explorer

app/assets/javascripts/widgets/brochure.js
Trello Card: https://trello.com/c/xdjPNy4h
Issue #307
=> Fixes View Menu button in one-column template.

.cascade-code/Chapman.edu/_cascade/blocks/html/global_footer.html, app/assets/javascripts/cascade/weather.js, app/views/_cascade/blocks/html/_footer.html, app/views/_cascade/blocks/html/_law_footer.html
change javascript and url params of link we are using to pull current temp via JSON hosted on forecast.chapman.edu
=> fix to weather.js for feed that gets current temperature

.cascade-code/Chapman.edu/_components/omni_nav_v2/omni_nav_v2.vtl
add site variable to internal links in dropdowns of omniNav (so can get new omniNav v2 to webfarm apps)
=> add site variable to internal links in dropdowns of omniNav

.cascade-code/Chapman.edu/_cascade/formats/Homepage_Blog_Stories
Fix so using right url field; add tests if external or internal link so get correct xml node; add escape function to title of link so special characters can be used
=>  Top Story on homepage not using right link fields for the Additonal Link 

.cascade-code/Chapman.edu/_components/omni_nav_v2/omni_nav_v2.vtl, .cascade-code/Chapman.edu/_config/global_nav.vm, app/views/omni_nav_v2/_global_nav.html.erb
Story: https://trello.com/c/daA5FyTd
Updates OURCA to CUE in global and off-canvas navs. I also updated the `_global_nav.html.erb` file, but the `_off_canvas_nav.html.erb` file did not have anything underneath "Research" for me to update. I can change that if we want.
=> Updates OURCA to CUE in global and off-canvas navs.

Gemfile, Gemfile.lock
Story: https://trello.com/c/HDVfXN8t
=> Update vulnerable dependencies.

app/assets/javascripts/omni_nav/google-custom-search.js, app/assets/javascripts/omni_nav/omni-nav-v2.js, app/assets/stylesheets/omni_nav/omni_nav_v2/omni-nav.scss
Story: https://trello.com/c/CjuMJuaB
=> Fix search box styling on Chapman.edu

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Funnels_1up, app/assets/stylesheets/widgets/primary_column/regions.scss, app/views/widgets/primary_content/_funnel_1up_boxes_1.html
Story: https://trello.com/c/gtcnl39R
=> As a WWW visitor, I want the 1-up Funnel headings to be the correct heading-level.

.cascade-code/Chapman.edu/_cascade/formats/helpers/primary_column_helpers.velocity, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/fact_cards_with_text.vtl, app/assets/javascripts/widgets/messaging_1_column.js, app/assets/stylesheets/components/section_message.scss, app/assets/stylesheets/widgets/single_column/messaging.scss, app/data_definitions/from_cascade/one_column.xml, app/views/widgets/single_column/_messaging_1_column.html, app/views/widgets/single_column/_messaging_1_column_facts.html, app/views/widgets/single_column/_messaging_1_column_image.html, app/views/widgets/single_column/_messaging_2_column.html, app/views/widgets/single_column/_messaging_2_column_facts.html, app/views/widgets/single_column/_messaging_2_column_text_left.html, app/views/widgets/single_column/_messaging_2_column_video_dark_bg.html, app/views/widgets/single_column/_messaging_2_column_vimeo_video.html, app/views/widgets/single_column/_messaging_2_column_with_bg_image.html, app/views/widgets/single_column/_messaging_2_column_youtube_video.html
merging Sean Stacho's changes to 1-column template widgets from development to master
=> As a WWW user, I would like to have a drop down on the 1 column in the following widgets: Text with video, Text with image, and Text.

app/assets/stylesheets/layout_old/main.scss, app/assets/stylesheets/layout_old/primary-content.scss, app/assets/stylesheets/widgets/single_column/chapman_social_feed.scss, app/assets/stylesheets/widgets/single_column/messaging.scss
story: https://trello.com/c/TKzDWgMo
=> In WWW, add dotted line under links on 1-column and landing pages - Development

.cascade-code/Chapman.edu/_cascade/discover/formats/Banner.vtl
Story: https://trello.com/c/ZKT6JD79
=> In WWW on Discover pages, add alt-text to image loader gif

.cascade-code/Chapman.edu/_cascade/discover/formats/Banner.vtl
Story: https://trello.com/c/ZKT6JD79
=> In WWW on Discover pages, add alt-text to image loader gif - Master

.cascade-code/Chapman.edu/_cascade/formats/Homepage_Blog_Stories, .cascade-code/Chapman.edu/_cascade/formats/Homepage_CU_Family_section, app/assets/javascripts/cascade/new-home.js, app/assets/stylesheets/widgets/home_page/blog_stories.scss, app/views/widgets/home_page/_blog_stories.html, app/views/widgets/home_page/_chapman_family.html
Story: https://trello.com/c/m70WEgMW
=> In www, remove the ability to share from the blogs widget

subprojects/degrees-and-programs/source/static/package-lock.json
Story: https://trello.com/c/ZKT6JD79
=> In Cascade Assets, fix security vulnerabilities identified by Github.

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, app/assets/stylesheets/omni_nav/omni_nav_v2/omni-nav.scss, app/views/widgets/shared/_header.html
Trello card: https://trello.com/c/rZo8vbPV/831-in-www-add-aria-label-attribute-to-links-in-global-nav
See changes:
http://dev-www.chapman.edu/index.aspx
=> Omninav keyboard accessibility

app/assets/stylesheets/themes/business__grad.scss
Story: https://trello.com/c/jCq65MUK
=> Apply new subbranding theme to business subpages in cascade-assets

app/assets/stylesheets/layout_old/right-column.scss, app/assets/stylesheets/themes/law.scss, app/controllers/content_types/modular_controller.rb
Story: https://trello.com/c/W7jY4BGc
=> Apply new subbranding theme to law subpages in cascade-assets

app/assets/javascripts/cascade/iframe-titles.js, app/assets/javascripts/master.js, app/assets/stylesheets/widgets/single_column/campus-map.scss
story: https://trello.com/c/4SHZIl5j
- add JS solution for untitled iFrames
- fix minor margin issue on campus map widget
=> add titles to untitled iFrames to appease Siteimprove; fix margin on Campus Map widget

app/assets/stylesheets/base/variables.scss, app/assets/stylesheets/widgets/single_column/chapman_stories_feed.scss, app/views/1_column/law_theme.html.erb
trello story: https://trello.com/c/zvwdFjD6/940-fix-stories-widget-styling-on-law-index
fixes on dev:
https://dev-www.chapman.edu/law/index.aspx
=> fix stories widget styling

app/assets/javascripts/cascade/iframe-titles.js
https://trello.com/c/4SHZIl5j
-resolves Wave-related errors
-respects existing iFrame titles
=> Adds script to add titles to untitled iFrames

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, app/assets/javascripts/cascade/footer.js, app/assets/stylesheets/layout_old/footer.scss, app/assets/stylesheets/omni_nav/omni_nav_v2/omni-nav.scss
https://trello.com/c/potLcSM3
-Removes OmniNav's JS-reliant elements based on /NavsNoJS/ directory
-Hides the weather widget based on /NavsNoJS/ directory
https://dev-www.chapman.edu/navsNoJS/demo.aspx 
https://dev-www.chapman.edu/navsNoJS/index.aspx
=> Package onmi navigation and footer for use on Admission's Slate product

.gitignore
.vscode/settings.json will no longer be tracked
=> add vscode settings to gitignore

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, .cascade-code/Chapman.edu/_config/global_nav.vm, app/assets/stylesheets/omni_nav/omni_nav_v2/off-canvas-nav.scss
https://trello.com/c/d9syslSb
Demo via Wave (non-visual change) at https://dev-www.chapman.edu/nick/off-canvas-utility-contrast-fix.aspx
=> Resolve utility nav contrast errors

.cascade-code/Chapman.edu/_cascade/formats/level/left_nav.vtl, .cascade-code/Chapman.edu/_cascade/formats/level/left_nav_no_siblings.vtl, .cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, app/assets/stylesheets/base/defaults.scss, app/assets/stylesheets/components/left-nav-ul.scss, static/_files/css/level_2013.css
Added symlink support into left_hand_nav and omninav
=> Add symlink support

.cascade-code/Chapman.edu/_cascade/formats/Faculty Directory/Main Listing.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Faculty Info Primarys.vtl, app/assets/javascripts/cascade/level/faculty.js, app/assets/stylesheets/widgets/primary_column/personnel_region.scss, app/data_definitions/from_cascade/Faculty Directory/faculty-profile-block.xml, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml
new Faculty Widget. Some was in production Cascade but never used. Some of this is new, some styling changes for the new widget, and a few files are brand new (were in Cascade but never in github). For the two and three column data definitionns, you should use the ?w=1 parameter in the url to compare the before and after for those files because much of the differences it shows are just spacing and tabbing differences. I need to push this live this week so appreciate a quick review and approval, if possible.
=> Faculty widget

.cascade-code/Chapman.edu/_cascade/blocks/html/global_footer.html, .cascade-code/Chapman.edu/_cascade/blocks/html/law_footer.html, app/assets/javascripts/cascade/footer.js, app/views/_cascade/blocks/html/_footer.html, app/views/_cascade/blocks/html/_law_footer.html
Story: https://trello.com/c/wEy8SydN
=> Footer Issues on WWW

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/mult_image-content-blocks.vtl, app/assets/stylesheets/widgets/single_column/multi-image-content-blocks.scss, app/controllers/content_types/modular_controller.rb, app/data_definitions/from_cascade/one_column.xml, app/views/1_column/law_theme.html.erb, app/views/widgets/single_column/_call_to_action_3_up.html
I added a "circle" option for the multi-image content blocks widget. You can see it here:
https://dev-www.chapman.edu/test-section/joey-test/Index2.aspx
=> added circle option for multi-image content blocks widget

app/assets/javascripts/components/skip-link.js, app/assets/javascripts/omni_nav/omni-nav-v2.js, app/assets/stylesheets/omni_nav/omni_nav_v2/off-canvas-nav.scss, app/views/layouts/home_page.html.erb, app/views/widgets/home_page/_hero_panel.html
fix issues #428 and #429
also small qol changes such as adding a focus outline for off-canvas nav X button and minor clean up
=> Fix omninav tab issues

.cascade-code/Chapman.edu/_cascade/formats/modular/mastheads/side_panel_hero.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/call_to_action_3_up.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/call_to_action_footer.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/contact_footer.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/fact_cards_with_text.vtl, app/assets/stylesheets/base/defaults.scss, app/assets/stylesheets/base/mixins.scss, app/assets/stylesheets/components/fact-card.scss, app/assets/stylesheets/components/new-button.scss, app/assets/stylesheets/layout_old/footer.scss, app/assets/stylesheets/themes/home.scss, app/assets/stylesheets/widgets/hero/side_panel.scss, app/assets/stylesheets/widgets/home_page/blog_stories.scss, app/assets/stylesheets/widgets/home_page/hero_panel.scss, app/assets/stylesheets/widgets/news-events-feed.scss, app/assets/stylesheets/widgets/primary_column/collapsibles.scss, app/assets/stylesheets/widgets/primary_column/tabs.scss, app/assets/stylesheets/widgets/single_column/call_to_action_3_up.scss, app/assets/stylesheets/widgets/single_column/call_to_action_block.scss, app/assets/stylesheets/widgets/single_column/contact_footer.scss, app/assets/stylesheets/widgets/single_column/cta_footer.scss, app/assets/stylesheets/widgets/sponsor-logo-rotator.scss, app/views/layouts/home_page.html.erb, app/views/widgets/hero/_side_panel.html, app/views/widgets/single_column/_call_to_action_3_up.html, app/views/widgets/single_column/_contact_footer.html, app/views/widgets/single_column/_cta_footer.html, app/views/widgets/single_column/_messaging_1_column_facts.html
Hi guys, could you take a look and do a review on this
Trello cards: 
1. https://trello.com/c/ct6NCsV7/1025-1-column-accessibility-review 
2. https://trello.com/c/rPBO3sPK/1026-2-3-column-accessibility-review
Summary:
- Some fixed headings
- Increased body text size
- Added focus outlines for several widgets
- Improved focus outlines for several buttons/widgets
Example pages:
1. https://dev-www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/web/1-column-modular-example-page.aspx
2. https://dev-www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/web/2-column-modular-example-page.aspx
3. https://dev-www.chapman.edu/campus-services/marketing-communication/guidelines-and-resources/web/3-column-modular-example-page.aspx
=> Template accessibility improvements

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl
(https://trello.com/c/OS6sjLE9 )
demo: https://dev-www.chapman.edu/law/index.aspx
=> fixes 'About' labels in Law dropdown 

.cascade-code/Chapman.edu/_cascade/blocks/html/typekit.html, .cascade-code/_chapman_common/_cascade/blocks/GOOGLE_TAG_MANAGER.html, app/assets/javascripts/cascade/accessibility__landmarks.js, app/assets/javascripts/master.js
Nothing major -- this:
- adds correct typekit block to version control (Joey already fixed this on Master)
- updates the Google Tag Manager block
- reverts #433
=> Rc monkey patches

app/assets/stylesheets/components/left-nav-sub-content.scss
Story: https://trello.com/c/d7TCD8e5
=> 2-3 column: Align white link box within the content block widget.

app/views/widgets/single_column/_chapman_social_feed.html
Story: https://trello.com/c/NiN7O5D5
=> WWW, Fix chapmanSocial js error

.cascade-code/Chapman.edu/_cascade/blocks/html/global_footer.html, .cascade-code/Chapman.edu/_cascade/blocks/html/law_footer.html, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Personnel.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/fact_cards_with_text.vtl, app/assets/stylesheets/base/mixins.scss, app/assets/stylesheets/layout_old/faculty/profile-page.scss, app/assets/stylesheets/widgets/primary_column/personnel_region.scss, app/views/_cascade/blocks/html/_footer.html, app/views/_cascade/blocks/html/_law_footer.html, app/views/widgets/primary_content/_personnel_anchors.html, app/views/widgets/primary_content/_personnel_region_1.html, app/views/widgets/primary_content/_personnel_region_2.html
Miscellaneous catchup of fixes (some done already on live site):
Accessibility fix to Personnel widget (names as headings and aria-label on Bio link); fixes to spacing in Global and Law Footer for copyright; change to sitewide line-spacing from 23px to 20px (Erica approved); removal of extraneous target and title params in links in Global and Law Footer blocks; fix to url/link in Law Footer block; change to line-spacing of some elements on faculty directory pages
=> Personnel widget and other minor fixes

app/assets/stylesheets/base/animations.scss, app/assets/stylesheets/layout_old/footer.scss
story: https://trello.com/c/6kz40g3R
=> WWW, Law footer is broken on mobile view

.cascade-code/Chapman.edu/_cascade/formats/helpers.velocity, .cascade-code/Chapman.edu/_cascade/formats/modular/Ad Landing/Mastheads.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/Ad Landing/widgets/masthead-hero.vtl, app/assets/stylesheets/layouts/ad_landing_page.scss, app/data_definitions/from_cascade/ad_landing.xml
Story: https://trello.com/c/wUBUU1M9 
Note: This requires a new Cascade Asset Factory (as noted in the Masthead-Hero.vtl comments)
=> Feature  lqip

app/assets/javascripts/cascade/campus-services-anchor-point-readjustment.js, app/assets/javascripts/master.js
story: https://trello.com/c/ZCjBDv9e
=> Feature  anchor point readjustment

.cascade-code/Chapman.edu/_cascade/blocks/html/global_footer.html, app/assets/javascripts/cascade/back-to-top.js, app/assets/javascripts/master.js, app/assets/stylesheets/layout_old/footer.scss, app/views/_cascade/blocks/html/_law_footer.html
story: https://trello.com/c/UOGowamS
=> Feature - back to top button

app/assets/javascripts/cascade/campus-services-anchor-point-readjustment.js
=> Hotfix - WYSIWYG Anchor Point

app/assets/stylesheets/regions/mastheads/brochure-masthead.scss
Story: https://trello.com/c/xdmoPrfp
Demo: https://dev-www.chapman.edu/test-section/nick-test/sprint-4-10-19/masthead-font-issue.aspx 
Spawned: https://trello.com/c/8Hk60Z0J
=> Fix - font issue brochure masthead

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, app/assets/javascripts/widgets/upgrade_alert.js, app/assets/stylesheets/themes/home.scss, app/assets/stylesheets/widgets/home_page/upgrade_alert.scss, app/views/layouts/home_page.html.erb
=> Update - minimum supported browser versions

.cascade-code/Chapman.edu/_cascade/formats/level/Masthead.vtl, app/data_definitions/from_cascade/two_column.xml
story: https://trello.com/c/pGYmCKim
demo: https://dev-cascade.chapman.edu/entity/open.act?id=7a56ec44c0a81e4b2afe10e7bbb6c60b&type=page // https://dev-www.chapman.edu/test-section/nick-test/sprint-5-8-19/masthead-remove-target-link.aspx
=> Remove  boxes masthead new window

.cascade-code/Chapman.edu/_cascade/formats/level/Masthead.vtl, app/assets/javascripts/cascade/level/rotator.js, app/assets/javascripts/cascade/rotator.js, app/assets/stylesheets/regions/mastheads/boxes-masthead.scss, app/views/_cascade/blocks/html/_cascade_assets.html, app/views/widgets/masthead/_boxes_1.html
(Outstanding) Story: https://trello.com/c/kgfON1C4
Resolves issues where 1) scrolling behavior was changed and 2) flexbox squeezed items together instead of hiding. This masthead is due for a redesign (see comment on card) and it was determined not worth putting additional work into until then. 
demo: https://dev-www.chapman.edu/test-section/nick-test/sprint-4-10-19/boxes-masthead-redux.aspx#
=> Accessibility - Boxes Masthead Tabbing

app/assets/javascripts/cascade/rotator.js, app/assets/stylesheets/regions/mastheads/boxes-masthead.scss
Mandy noticed https://dev-www.chapman.edu/our-faculty/index.aspx was not loading as expected. This appears to resolve the issue, related a JS conflict in the new boxes-masthead accessibility (#477). 
Also trying out GH's 'Draft' Pull Request -- is there a better approach to the JS issue?
=> Hotfix - boxes masthead js conflicts

app/assets/stylesheets/regions/mastheads/boxes-masthead.scss
decreases top margin on the Boxes Masthead 'next' button:
https://dev-www.chapman.edu/research/center-for-undergraduate-excellence/index.aspx#
=> offset boxes masthead 'next' arrow

app/assets/stylesheets/themes/communication.scss
story: https://trello.com/c/rUKhjtWV
demo: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-6-2019/school-comm-standard-colors.aspx
=> change Comm theme colors to default cu-red

.cascade-code/Chapman.edu/_cascade/formats/Faculty Directory/Main Listing.vtl, app/assets/javascripts/cascade/level/faculty.js, app/assets/stylesheets/base/defaults.scss, app/assets/stylesheets/layout_old/faculty/profile-page.scss, app/assets/stylesheets/widgets/primary_column/personnel_region.scss, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml
Tweaks to Faculty Directory for new Physical Therapy codes (and also put in the real new codes for Engineering, were placeholders before)
=> Phys therapy changes to faculty directory v2

app/_cascade_assets/global/variables.scss
before: https://www.chapman.edu/communication/support.aspx
after: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-6-2019/communication/support.aspx
=> update comm scss variable to match default values

app/assets/javascripts/widgets/homepage-newsroom.js
If node parser app is fails tries staging node parser and if staging node parser fails sets widget stories to hard coded stories
=> fail checks for if node parser is down on prod and staging

app/assets/stylesheets/widgets/primary_column/funnel_boxes.scss
story: https://trello.com/c/UdPrujHe
before: https://www.chapman.edu/engineering/academic-programs/index.aspx
after: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-19-2019/cascade-left-image-align-on-a-photo-doesnt-function-properly.aspx
=> Defect - Resolves mobile word wrapping issue on 2col funnel up widget

app/views/layouts/cascade-assets.xml.erb
story: https://trello.com/c/r8f8HBOb
demo: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-19-2019/cascade-assets-timestamp-branch.aspx
=> Feature - timestamp cascade assets zip

app/assets/javascripts/widgets/homepage-newsroom.js
story: https://trello.com/c/IXU7SYMG
=> Update the homepage newsroom widget category

.cascade-code/Chapman.edu/_cascade/formats/Alert.vtl, .cascade-code/Chapman.edu/_cascade/formats/Open Graph And Canonical Tags.vtl, .cascade-code/Chapman.edu/_config/global_nav_law.vm, app/assets/stylesheets/base/defaults.scss, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml
Misc:
For the the OG And Canonical Tags format, I'm fixing an issue with duplicates of the meta tags (I think the previous Developer tried to group the meta tags together with the new ones for twitter but left them in 2 places in the file, plus removed the fully-qualified domain which we need so adding back.
Fix to remove Panther from Panther Alert heading in the homepage alert.
Small update to 2 links in Law's global nav  menu
Updates to depts in dropdown for Faculty Widget in the 2 and 3 Column Data Definitions.
style for table captions.
=> Misc format and block fixes

app/assets/stylesheets/layouts/three_column.scss
story: https://trello.com/c/YKuuU27o
demo: https://dev-www.chapman.edu/test-section/nick-test/3col-moble-priority.aspx
=> Update 3 col priority of primary/right/left on mobile view

.cascade-code/Chapman.edu/_cascade/templates/Modular/1_column.html, .cascade-code/Chapman.edu/_cascade/templates/Modular/2_column.html, .cascade-code/Chapman.edu/_cascade/templates/Modular/3_column.html, .cascade-code/Chapman.edu/_cascade/templates/Modular/ad_landing.html, .cascade-code/Chapman.edu/_cascade/templates/home_page_v3.html
DEFAULT region meant to replace PRIMARY CONTENT region. For now leave both. Make change to the Ad Landing, 1 Column, 2 and 3 Column Modular templates
=> add DEFAULT region to the Modular templates

.cascade-code/Chapman.edu/_cascade/formats/modular/PrimaryContent.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Form Embed.vtl, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml
new Form Embed widget for 2 and 3 Column Modular pages; A few additional tweaks for depts in Faculty Info widget in data defs; Also adding PrimaryContent velocity format to github for first time, though not new in Cascade.
=> New form embed widget

app/assets/stylesheets/base/defaults.scss, app/assets/stylesheets/layout_old/primary-content.scss
decrease heading margin to .5rem; decrease paragraph line-height as per Erica's recommendations
=> decrease default heading margin to .5rem; decrease paragraph line-height 

app/assets/javascripts/cascade/faculty-directory/school-listing.js
Engineering's faculty page moved and the path is the trigger to filter which faculty display on this .Net page. Update the decode in javascript
=> update path to Engineering page to trigger filter

app/assets/stylesheets/base/defaults.scss
https://trello.com/c/3rgu0Fbb
demo: https://dev-www.chapman.edu/test-section/index.aspx
=> update global paragraph margin-bottom

lib/tasks/build.rake
https://trello.com/c/udLkMYa9
Adds a changelog to the ./dist folder
=> add git status and git whatchanged to ./distchangelog.log

.cascade-code/Chapman.edu/_cascade/formats/modular/LeftColumnContent.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/PrimaryContent.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Shared Content - Dept Contacts Left Column.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Shared Content - Dept Contacts Primary Content.vtl, app/assets/stylesheets/components/callout.scss, app/assets/stylesheets/components/left-nav-sub-content.scss
changes to font and heading styles and how pull in some of the data fields in the Dept Contact widget for the Left Column. For some formats, just bringing them to github for the first time but they already existed in Cascade.
=> Fixes to Dept Contact LC widget

.cascade-code/Chapman.edu/_cascade/blocks/html/global_footer.html, .cascade-code/Chapman.edu/_cascade/blocks/html/law_footer.html, app/views/_cascade/blocks/html/_footer.html, app/views/_cascade/blocks/html/_law_footer.html
Change link label from Accessibility to Accessibility Feedback since goes to form not that whole site
=> update link label

.cascade-code/Chapman.edu/_cascade/blocks/html/global_footer.html, .cascade-code/Chapman.edu/_cascade/blocks/html/law_footer.html, app/assets/javascripts/widgets/homepage-newsroom.js, app/views/_cascade/blocks/html/_footer.html, app/views/_cascade/blocks/html/_law_footer.html
update link label in Global and Law Footer blocks so says Accessibility Feedback and not just Accessibility
=> update Footer links to say Accessibility Feedback

app/assets/javascripts/cascade/level/accordion.js
Followup request to https://github.com/chapmanu/cascade-assets/pull/554
=> Update  accordion toggle verbiage

app/assets/stylesheets/omni_nav/omni_nav_v2/off-canvas-nav.scss
https://trello.com/c/Gt0kbvix
Before
https://www.chapman.edu/engineering/
After
Fowler: https://dev-www.chapman.edu/engineering/index-omninav-breakpoint-fix.aspx
Example without secondary logo: https://dev-www.chapman.edu/test-section/nick-test/omninav-breakpoint-homepage.aspx
=> resolves omninav breakpoint issue @media <= 1398px 

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Featured_News_Events_Left_Col.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Featured_News_Events_Primary_Content.vtl, app/assets/javascripts/cascade/level/news-events.js
missed updating a new rss feed in the news/events javascript; also removed a class in news/event that was in github but not production Cascade (and not a change I made in github)
=> News events feed update

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, app/assets/javascripts/widgets/upgrade_alert.js, app/assets/stylesheets/components/upgrade-alert.scss, app/views/omni_nav_v2/_omninav.html.erb, app/views/omni_nav_v2/omninav.html.erb
followup to #553. Enabling upgrade alert now that Change Management has approved and requested this timeframe
=> Enable browser upgrade alert

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Collapsibles.vtl, .cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, app/assets/javascripts/cascade/level/accordion.js, app/assets/javascripts/widgets/upgrade_alert.js, app/views/widgets/primary_content/_collapsables_2.html
Story: https://trello.com/c/dbz1uoxR
Story: https://trello.com/c/u5qINseg
=> Merging Development into master

.cascade-code/Chapman.edu/_cascade/formats/modular/1 Column Primary Content.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/mult_image-content-blocks.vtl, app/assets/stylesheets/widgets/single_column/multi-image-content-blocks.scss
Multi Image Block Fix (for PJ https://trello.com/c/PQVQHddA)
before (‘Test Block for Development’ near footer): https://wwwtest.chapman.edu/law/index-new.aspx
after: https://dev-www.chapman.edu/test-section/nick-test/multi-image-content-block__padding-etc.aspx
=> Multi image content block - defect -- padding

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl, .cascade-code/Chapman.edu/_config/global_nav.vm, app/views/widgets/shared/_header.html
various recently requested fixes to urls, or additions of links, in the omniNav. Some in Global Nav, others in Login section or off-canvas menu.
=> fixes or additions to links in OmniNav

app/assets/stylesheets/components/wysiwyg-buttons.scss, app/views/widgets/primary_content/_wysiwyg_editor_3.html
https://trello.com/c/NjdHBPf9
This includes the styles for the custom WYSIWYG buttons.
Note that the global WYSIWYG Editor Configuration must be configured via the GUI ( https://dev-cascade.chapman.edu/administration/dashboard.act -> "System Default WYSIWYG Editor Configuration" )
See https://dev-cascade.chapman.edu/entity/open.act?id=DEFAULT&type=editorconfiguration for an example
=> wysiwyg - cta buttons

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Collapsibles.vtl, app/assets/stylesheets/widgets/primary_column/collapsibles.scss, app/views/widgets/primary_content/_collapsables_1.html, app/views/widgets/primary_content/_collapsables_2.html, app/views/widgets/primary_content/_collapsables_3.html
=> Collapsible widget  redesign

app/assets/javascripts/cascade/back-to-top.js, app/assets/stylesheets/omni_nav/uninav/uninav__ie.scss
CTA buttons justification is not ideal on ie11, but getting to this point took nearly the whole weekend + today
before: <img width="1434" alt="Screen Shot 2020-02-14 at 10 02 47 PM" src="https://user-images.githubusercontent.com/8109093/74685435-6aa53900-5183-11ea-8dcd-50ebf442692a.png">
after: <img width="1440" alt="Screen Shot 2020-02-17 at 12 43 29 PM" src="https://user-images.githubusercontent.com/8109093/74685416-595c2c80-5183-11ea-999f-13180e3a8b04.png">
view https://dev-www.chapman.edu/test-section/index.aspx on browserstack
=> add CSS fixes, targeting ie11

.cascade-code/Chapman.edu/_cascade/formats/modular/uninav/_mobile_hamburger_toggle_icon.vtl, .gitignore, app/assets/javascripts/uninav/offcanvas-nav.js, app/assets/stylesheets/omni_nav/uninav/uninav-offcanvas.scss, app/assets/stylesheets/omni_nav/uninav/uninav.scss, app/views/uninav/_hamburger.html.erb
Changes include mobile resizing for offcanvas
=> Dev to staging merge into development 

.cascade-code/Chapman.edu/_cascade/formats/helpers.velocity
removed chapman site variable from drilldown href
=> Dev to staging into development

.cascade-code/Chapman.edu/_cascade/formats/modular/uninav/_global.vtl, app/assets/javascripts/uninav/uninav.js, app/assets/stylesheets/omni_nav/uninav/uninav.scss, app/views/uninav/_global_nav.html.erb
Story: https://chapman.my.workfront.com/task/view?ID=5e68212f0136cb741e0c285edc53c4ec
Keeps padding between 'Global Nav' proportional; was previously equal widths via flex
https://dev-www.chapman.edu/test-section/globalnav-pipes.aspx
=> Uninav - Globla Menu Padding

.cascade-code/Chapman.edu/_cascade/formats/Homepage_Blog_Stories.vtl, .cascade-code/Chapman.edu/_cascade/formats/Homepage_CU_Family_section.vtl, .cascade-code/Chapman.edu/_cascade/formats/home/Homepage News Stories.vtl, app/views/uninav/home_page.html.erb, app/views/widgets/home_page/_blog_stories.html, app/views/widgets/home_page/_chapman_family.html, app/views/widgets/home_page/_newsroom_stories.html
Addresses multiple landmarks accessibility issue
https://trello.com/c/dFeDm4m5
https://dev-www.chapman.edu/test-section/nick-test/multiple-footer-landmarks.aspx
=> Homepage Stories Widgets - change <footer> to <div>

.cascade-code/Chapman.edu/_cascade/formats/modular/PrimaryContent.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/uninav/uninav.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/RSS Feed Display.vtl, Gemfile.lock, app/assets/javascripts/widgets/rss_feed_display.js, app/assets/stylesheets/widgets/rss-feed-display.scss, app/controllers/content_types/modular_controller.rb, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml, app/views/widgets/primary_content/_rss_feed_display.html
Story: https://chapman.my.workfront.com/task/view?ID=5e7bc0c9027160dee25d5e0b5cb36014
=> Create rss feed widget

.cascade-code/Chapman.edu/_cascade/formats/modular/uninav/_audiences.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/uninav/_global.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/uninav/_globalNav_menu.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/uninav/_offCanvas_main_menu.vtl
Story: https://chapman.my.workfront.com/task/view?ID=5e8cefa604bec53f14b1beadf3f452cb
=> Fix relative links on webfarm

.cascade-code/Chapman.edu/_cascade/formats/modular/PrimaryContent.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Text with CTA.vtl, app/assets/stylesheets/widgets/primary_column/text-with-cta.scss, app/controllers/content_types/modular_controller.rb, app/data_definitions/from_cascade/two_column.xml, app/views/widgets/primary_content/_text_with_cta.html
Story: https://chapman.my.workfront.com/task/view?ID=5e7bc0fb0271b14278eacfc7aa04ffd1
=> 2 column CTA Widget

.cascade-code/Chapman.edu/_cascade/templates/Faculty Directory/main_listing.html, .cascade-code/Chapman.edu/_cascade/templates/Faculty Directory/profile_page.html, .cascade-code/Chapman.edu/_cascade/templates/Faculty Directory/school_dept_listing.html, .cascade-code/Chapman.edu/_cascade/templates/Modular/1_column.html, .cascade-code/Chapman.edu/_cascade/templates/home_page_v3.html, .cascade-code/_chapman_common/_cascade/blocks/GOOGLE_TAG_MANAGER.html, app/views/_cascade/templates/modular/three_column.html, app/views/_cascade/templates/modular/two_column.html, app/views/uninav/two_column.html.erb
https://chapman.my.workfront.com/project/view?ID=5e31a476024947873ade818e62cf0a60&commentID=5e8642c40510b6c7a55b1168a1f39a01&activeTab=tab-project-updates&showCommentBox=true
=> Add Howard's Requested Changes

app/assets/stylesheets/widgets/primary_column/next-steps-widget.scss, app/controllers/content_types/modular_controller.rb, app/views/widgets/primary_content/_next_steps_widget.html
https://recordit.co/P3S8LHXflN
=> Next Steps Widget - increase <a> line height

.cascade-code/Chapman.edu/_cascade/formats/level/Breadcrumbs.xslt, .cascade-code/Chapman.edu/_cascade/formats/level/social_accounts.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/uninav/_search.vtl, app/assets/stylesheets/components/breadcrumbs.scss, app/assets/stylesheets/omni_nav/uninav/uninav-placeholder.scss, app/controllers/content_types/modular_controller.rb, app/views/uninav/two_column.html.erb, app/views/widgets/shared/_breadcrumbs.html, app/views/widgets/shared/_head.html
story: https://chapman.my.workfront.com/task/view?ID=5e7a79210103a796874ce0202e658d5c
demo: https://dev-www.chapman.edu/crean/academic-programs/undergraduate-programs/ba-psychology/breacrumbs-ba-psychology.aspx
=> Breadcrumbs redesign

.cascade-code/Chapman.edu/_cascade/formats/Homepage_Current_Hero_panel.vtl, app/assets/javascripts/cascade/level/homepage-masthead.js, app/assets/stylesheets/widgets/_ad_landing_page/homepage_masthead.scss, app/data_definitions/from_cascade/home_page.xml, app/views/uninav/home_page.html.erb
story: https://chapman.my.workfront.com/task/5ee9413d01da4600f339c540c3a5a3a1/updates
demo: https://dev-www.chapman.edu/test-section/nick-test/homepage-masthead-curator-spans.aspx
=> Homepage masthead  curatorio images

app/assets/stylesheets/widgets/primary_column/testimonial_widget.scss, app/views/uninav/two_column.html.erb
https://chapman.my.workfront.com/task/5efbb0c900b0103910ff1abb2f956a33/updates
=> update testimonial widget slider button box shadow

.cascade-code/Chapman.edu/_cascade/formats/level/Masthead.vtl, app/assets/javascripts/cascade/level/rotator.js, app/assets/javascripts/cascade/plugins/formstack.js, app/assets/javascripts/cascade/rotator.js, app/assets/javascripts/master.js, app/data_definitions/from_cascade/three_column.xml, app/data_definitions/from_cascade/two_column.xml, static/_files/css/formstack.css
See https://docs.google.com/spreadsheets/d/1_A9D5Mx0WVnEtOnTNJ3NWEgzFE9aV6qAWlcOLqzB9z4/edit#gid=0
=> Nick + Joey accessibility fixes 8 2020

.cascade-code/Chapman.edu/_cascade/formats/modular/mastheads/brochure_masthead.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/image_slider_widget.vtl, app/assets/javascripts/cascade/plugins/hero-slider.js, app/assets/javascripts/cascade/plugins/lightslider.js, app/assets/javascripts/cascade/plugins/slick.js, app/assets/javascripts/widgets/homepage-newsroom.js, app/assets/javascripts/widgets/image_slider.js, app/assets/stylesheets/base/defaults.scss, app/assets/stylesheets/plugins/slick.scss, app/assets/stylesheets/plugins/slick_theme.scss, app/assets/stylesheets/regions/mastheads/brochure-masthead.scss, app/assets/stylesheets/widgets/single_column/image_slider.scss, app/views/layouts/application.html.erb, app/views/uninav/two_column.html.erb, app/views/widgets/masthead/_brochure.html, app/views/widgets/single_column/_image_slider_2018.html.erb
https://chapman.my.workfront.com/task/5f59471d0a87800e045b4586cc19f162/updates
=> Pause Brochure Masthead, Image Slider

app/assets/stylesheets/widgets/primary_column/testimonial_widget.scss, app/assets/stylesheets/widgets/primary_column/text-with-cta.scss, app/controllers/content_types/modular_controller.rb
Note: Originally from 9/24. I neglected to add you all as reviewers, and forgot about it. 
https://chapman.my.workfront.com/task/5f6bd55d0c4d52e8251c3c6e2e52293a/updates
https://dev-www.chapman.edu/test-section/nick-test/3-col-testimonial-padding.aspx
=> Testimonial Widget (3 col) - fix padding

app/assets/javascripts/widgets/homepage-newsroom.js
Fixes issue with homepage featured story linking to backup story
=> Homepage news stories hotfix

lib/tasks/web-services.rake
https://chapman.my.workfront.com/task/5f7e485004157ac67868fe9df7ec9b29/updates
=> Fix cascade web services (edit_cascade_assets rake task)

app/assets/javascripts/cascade/level/orgsync-link-removal.js
https://chapman.my.workfront.com/task/5fb5b27e0066137b7d11a9da73fa5d0f/updates
This is already live on production
=> Replace dead orgsync links with https://chapman.campuslabs.com/engage.

.cascade-code/Chapman.edu/_cascade/formats/helpers.velocity, .cascade-code/Chapman.edu/_cascade/formats/homepage_featured_callouts.vtl, .cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Grid-Block-Widget.vtl, .cascade-code/Chapman.edu/_cascade/templates/home_page_v3.html, app/assets/stylesheets/base/defaults.scss, app/assets/stylesheets/base/variables.scss, app/assets/stylesheets/widgets/home_page/featured_callouts.scss, app/assets/stylesheets/widgets/primary_column/next-steps-widget.scss, app/data_definitions/from_cascade/Home_Page_v3.xml, app/views/home_page/sample.html.erb, app/views/uninav/home_page.html.erb, app/views/widgets/home_page/_featured_callouts.html, config/initializers/assets.rb, lib/tasks/push-local-assets.rake, lib/tasks/web-services.rake, lib/tasks/web-services/push-local-assets.rake
https://chapman.my.workfront.com/task/6064f498000405827c15d035fe7e6264/documents
=> Homepage ads

app/views/widgets/single_column/_chapman_stories_feed.html, lib/assets/javascripts/chapman_stories_feed.js
Added more checks before moving the feed buttons when multiple instances of this widget are being used on the same page.
=> Fixed Feed Buttons for multiple Stories Feed widget instances on the same page

app/assets/stylesheets/widgets/home_page/hero_panel_masthead.scss, app/assets/stylesheets/widgets/home_page/inspire.scss
https://www.chapman.edu/test-section/david-test/homepage-index-20230525.aspx
=> Updated masthead to reflect new adjustments
