app/controllers/content_types/modular_controller.rb
app/data_definitions/ad_landing.rb
app/data_definitions/base.rb
app/data_definitions/from_cascade/one_column.xml
app/data_definitions/one_column.rb
app/models/configuration_set.rb
app/views/_cascade/formats/modular/_one_column_masthead.erb
app/views/_cascade/formats/modular/ad_landing/widgets/_masthead_hero.html.erb
app/views/_cascade/formats/modular/mastheads/_side_panel_hero.erb
app/views/dashboard/index.html.erb
lib/tasks/build.rake

This is an action item I worked on while waiting on product owners to review current story.
It enhances the one-column modular example in Cascade Assets and tweaks some of the patterns for mirroring Cascade behavior.

In Cascade Assets `ContentTypes::ModularController`, move logic for `spike` action into `one_column` and remove `spike` route.

---

app/assets/javascripts/omni-nav.js
app/views/_cascade/blocks/html/_cascade_assets.html
app/views/widgets/shared/_head.html
test/features/home_page_sample_test.rb
test/features/modular_one_column_test.rb

Fixes Issue #92.
This was uncovered while releasing this story:
https://trello.com/c/uRGgv3TA/111-defect-when-embedding-a-third-party-civic-engagement-widget

Hamburger menu in omninav is not functioning.

---

app/assets/stylesheets/widgets/home_page/hero_panel.scss
app/views/widgets/home_page/_hero_panel.html

- Applied span styles on sample.
- Changed subheading weight to 100 per Ross. Removed excerpt class from 480px mobile view. Corrected media query from 780 to 768. Fixed heading padding to fit appropriate media.

Homepage h2 subheading class fix

---

app/assets/javascripts/cascade/level/news-events.js
app/views/2_column/sample.html.erb
app/views/3_column/sample.html.erb
app/views/widgets/left_column/_shared_content_contacts_1.html
app/views/widgets/left_column/_shared_content_contacts_2.html
app/views/widgets/left_column/_shared_content_contacts_3.html

Contains an edit to the news/events javascript to include paths for CDC events feed, and CES news and events feeds.
Also has 3 new snippets of code for sample html for the Left Column Shared Content CONTACTS widget, embedded them into the Two and Three Column sample pages so Wai can work on styling them in localhost env.

CDC/CES options to news/events widget AND sample snippets for Left Col Shared Content

---

app/assets/stylesheets/layout_old/faculty/profile-page.scss

photos overlapping rank and additional titles when they are so long they
span the page, giving more top margin to photo. Issue seen on http://www.chapman.edu/our-faculty/peter-mclaren

add top margin to profilePicture for faculty profile

---

app/assets/javascripts/cascade/level/shared-content-dept-contacts.js
app/assets/javascripts/master.js
app/assets/stylesheets/components/icomoon.scss
app/assets/stylesheets/components/left-nav-sub-content.scss
app/assets/stylesheets/themes/business.scss
app/assets/stylesheets/themes/ces.scss
app/assets/stylesheets/themes/communication.scss
app/assets/stylesheets/themes/copa.scss
app/assets/stylesheets/themes/copa__dance.scss
app/assets/stylesheets/themes/copa__music.scss
app/assets/stylesheets/themes/copa__theatre.scss
app/assets/stylesheets/themes/crean.scss
app/assets/stylesheets/themes/dodge.scss
app/assets/stylesheets/themes/law.scss
app/assets/stylesheets/themes/pharmacy.scss
app/assets/stylesheets/themes/scst.scss
app/assets/stylesheets/themes/wilkinson.scss
app/views/3_column/law_theme.html.erb
app/views/3_column/sample-college.html.erb
app/views/3_column/sample.html.erb
app/views/widgets/left_column/_shared_content_contacts_1.html
app/views/widgets/left_column/_shared_content_contacts_2.html
app/views/widgets/left_column/_shared_content_contacts_3.html

adding new widget for Dept Contacts which uses shared content blocks in Cascade. New sample snippets for 2 and 3 Column pages for localhost testing, new SVG for social follow us icons, new JS for view more/less expander on widget; update to school themes for same widget

left column shared-content Dept Contacts widget

---

lib/omninav/builder.rb

- Issue #200 
- Trello Card: https://trello.com/c/xoZhXFCI
The issue was a little different than we originally thought. It's not that we had duplicate title for different elements. According to WAVE the issue is that we have links where the title attr is the same as the label. For example:
<a href="/" title="My Label">My Label</a>
WAVE reports screen readers don't need the title in this case and it should only be included if it offers some kind of additional advice to user.

In OmniNav off-canvas nav, fix ADA issue caused by conflicting link titles.

---

app/assets/stylesheets/layout_old/right-column.scss

https://trello.com/c/jnlQkoKK
See [trello comment](https://trello.com/c/jnlQkoKK/583-some-3-column-template-pages-on-www-are-appearing-with-margins-and-column-widths-not-consistent-with-the-standard#comment-59f367015d6c17c5945ab926) for explanation of issue

Some 3-column template pages on www are appearing with margins and column widths not consistent with the standard.

---

app/assets/stylesheets/components/flexslider.scss

Story: https://trello.com/c/Wbfhf5Ry
Just removes the rounded borders in the masthead. I looked around and didn't see anything else affected negatively.
This has already been approved but was recreated cause I accidentally branched off of development in the previous pull request: https://github.com/chapmanu/cascade-assets/pull/269.

Removes rounded borders for flexslider in masthead.

---

.cascade-code/Chapman.edu/_components/omni_nav_v2/omni_nav.vtl

Story: https://trello.com/c/H530g9YQ
These changes will let us use any kind of nested umbrella category, if there are multiple under the same root folder, listed in any order under $umbrellaCategories

As an OmniNav user on WWW, I want to be able to quickly access non-root umbrella categories through the off-canvas menu.

---

app/data_definitions/from_cascade/shared_content_degree_program.xml
app/data_definitions/from_cascade/shared_content_department_contact.xml
app/data_definitions/from_cascade/three_column.xml
app/data_definitions/from_cascade/two_column.xml
app/views/widgets/single_column/_contact_footer.html

None of these 5 changes will compile into a new cascade-assets; I was simply updating Data Definitions for the 2 and 3 Column Modulars to add some options in 2 dropdowns which I just made in production. The copies of the Data Defs in github were not current (even before my changes) with what's in production, so mostly just syncing them up. I also added 2 Data Defs that are in Cascade but not in github yet (the 2 for Shared Content blocks that we use for both Degrees and the Dept Contacts widgets). Last, I added an href to the Contact Footer in 1 Column sample html to match a change I made to a velocity format. Again, none of this rolls into a new deploy. They are all just sample code or saved copies of things in Cascade.

Changes to Data Defs stored in github to sync with production; updates to sample html

---

.cascade-code/Chapman.edu/_cascade/blocks/html/global_footer.html
app/assets/javascripts/cascade/weather.js
app/views/_cascade/blocks/html/_footer.html
app/views/_cascade/blocks/html/_law_footer.html

In weather.js  the url to json feed of current temperature was using callback=? as url param, and now we need to use callback=orange per Nikos H. in Schmid College; also fixing links in footer blocks to link to forecast.chapman.edu with https as they installed an SSL certificate awhile back

Fix to script for weather feed to get current temp

---

app/assets/javascripts/omni_nav/google-custom-search.js
app/views/omni_nav_v2/_off_canvas_nav.html.erb
app/views/widgets/home_page/_hero_panel.html

Story: https://trello.com/c/Am9ZQTZP
Just removed the javascript that added alt text to the image that google inserts in the custom search code. This was deemed the best solution because it doesn't introduce any errors, and it seems pretty likely that Google will change their class names again at some point so this was a bad way to do it.
I have not yet deployed to staging.

[Urgent] Fix OmniNav search function on Chapman.edu

---

.cascade-code/Chapman.edu/_cascade/formats/Homepage_Blog_Stories

The Additional Link field (ExtraLink) in the Top Story was pulling in a different
link field; Changed it to pull correct field(s), and test for internal vs
external; Followed conventions Tom had already established in this file previously when he refactored it.

Top Story on homepage not using right link fields for the Additonal Link

---

app/assets/stylesheets/widgets/primary_column/regions.scss

demonstrated fix: https://dev-www.chapman.edu/campus-life/index.aspx
At max-width: 767px breakpoint, image will lose float and text will drop below.

Fix funnels-1up widget on mobile

---

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Featured_News_Events_Left_Col
.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Featured_News_Events_Primary_Content
app/assets/javascripts/cascade/level/news-events.js
app/data_definitions/from_cascade/three_column.xml
app/data_definitions/from_cascade/two_column.xml
app/views/widgets/left_column/_news_event_left_col.html
app/views/widgets/left_column/_news_events_1.html
app/views/widgets/primary_content/_featured_news_events_feed_1.html

for the Default news feed and default link for View All News in the News and Events widget (2 and 3 Column Modular templates), change from blogs.chapman.edu/news-and-stories to news.chapman.edu

News instead of blogs feed

---

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl

the page for Financial Aid Calculator was moved so just fixing link in omniNav to reflect. Already made changes in live site to this format on the day the page was moved. This is to sync github to same changes.

Omni nav link fix for Financial Aid Calculator

---

.cascade-code/Chapman.edu/_cascade/formats/level/left_nav.vtl
.cascade-code/Chapman.edu/_cascade/formats/level/left_nav_no_siblings.vtl

add escapeTool.xml to several child or grandchild links in the 2 velocity formats that produce the Lefthand menus so symbolic links that have special chars in the url won't produce errors in the xml parsing

add escapeTool.xml function to child A tag urls

---

app/assets/javascripts/cascade/accessibility__landmarks.js
app/assets/javascripts/master.js

(followup to #432)
This is a novel approach that appeases Siteimprove's remaining Info and `Relationships 1.3.1 > Content not included in landmarks`. Since I'm using the extension to test, I'm unsure if this will work from Siteimprove's dashboard, as it may run before the JS fires ([like the iFrame title issue, which Wave doesn't flag ](https://trello.com/c/zYKQAVQq)). 
You can preview it at https://dev-www.chapman.edu/test-section/nick-test/index1.aspx

resolves remaining  'Content not included in landmarks' alerts

---

.cascade-code/Chapman.edu/_cascade/blocks/html/typekit.html
.cascade-code/_chapman_common/_cascade/blocks/GOOGLE_TAG_MANAGER.html

GTM cannot be included in a div/section tag despite Siteimprove's nagging. 
Typekit's prefetch solution created a poor UX

Revert GTM, Typekit

---

.cascade-code/Chapman.edu/_cascade/blocks/html/no_script.html

In #431, deferring master JS for improved load times introduced a poor UX issue wherein the "Some of the content on this website requires JavaScript to be enabled" alert flashes for a split second before the page loads. This is related to `<div class="noscript">` vs `<noscript>`. This PR resolves the issue. 
Demo: https://dev-www.chapman.edu/academics/index.aspx

Resolves flash of disabled JS alert

---

.cascade-code/Chapman.edu/_cascade/formats/Homepage UG Admission Section
.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl
.cascade-code/Chapman.edu/_config/global_nav.vm

https://trello.com/c/bNrtZRm5
Address Siteimproves "Link text used for multiple different destinations". 
Some sections use the same text to describe different links, eg `"Alumni" > "Get Involved" (https://dev-www.chapman.edu/alumni/get-involved/index.aspx)` and `"Support" > "Get Involved" (https://dev-www.chapman.edu/support-chapman/get-involved.aspx)` .  I've applied aria-labels where appropriate.
You can demo with the Siteimprove extension at https://dev-www.chapman.edu/test-section/nick-test/index1.aspx and compare against the former issues at https://my2.siteimprove.com/Inspector/10993/Accessibility/Page?pageId=31903631364&impmd=0D6974F8A4BBF3C0E325AAA2E369A7D2#/Criterion/2.4.4/Check/39
Note that Siteimprove 2.4.4 will now always display "Does the "aria-label" accurately describe the …

Accessibility  siteimprove 2.4.4

---

app/views/_cascade/blocks/html/_footer.html
app/views/_cascade/blocks/html/_law_footer.html

related to https://trello.com/c/UOGowamS and a hotfix pushed today for a flex display issue in the Footer on Safari 10.1

Update - back to top button

---

lib/tasks/serve.rake

story: https://trello.com/c/QEGyufbO
After `rake serve`, `rake serveo` in a new terminal tab/window will initiate a local tunnel prefixed with your OS username (eg `https://nnadel.serveo.net`). I experimented with ngrok and localtunnel but opted for Serveo because:
1) it's simpler 
2) no installation 
3) free subdomains. 
Sometimes the Serveo connection closes and you have to run the task again, so down the road it might make sense to switch to one of the others (pending usefulness, uptime, reliability, etc...). 
Once `rake serveo` fires, you can deduce your local asset files and replace existing (copy and paste for now) references (`<link href="https://nick.serveo.net/_assets/master.self.css" media="all" rel="stylesheet"/>`) in your personal cascade-assets block (eg `cascade-assets-nick` …

add rake task to initiate local tunnel

---

.cascade-code/Chapman.edu/_cascade/formats/Open Graph And Canonical Tags.vtl

story: https://trello.com/c/rTL5A1Fy
Due to the ip restrictions on the staging servers, Product Owners can't easily verify link previews via https://cards-dev.twitter.com/validator and requested we push to production for them to verify. For my own testing, I saved a static copy of a page and running a local server (eg npx http-server [path] [options]) + tunnel (ssh -R chaptwitter:80:localhost:8222 serveo.net)

Feature - Add Twitter Card Summary

---

.cascade-code/Chapman.edu/_cascade/formats/level/Masthead.vtl
app/assets/javascripts/cascade/rotator.js
app/assets/stylesheets/regions/mastheads/boxes-masthead.scss
app/data_definitions/from_cascade/three_column.xml

Follow-up to #475. I'd previously only removed the 'Same/New Window' section from the 2 Column Data Definition. This removes it from the 3 Column Data Definition and adds a few improvements to accessibility:
1) single tab through `<li>`s
2) scroll to 'Skip Carousel' on focus
story: https://trello.com/c/pGYmCKim
demo: https://dev-www.chapman.edu/test-section/nick-test/sprint-5-8-19/epay-123.aspx#

Fix - boxes masthead 3 col new target window

---

app/assets/stylesheets/themes/home.scss
app/assets/stylesheets/widgets/home_page/upgrade_alert.scss

Resolves global styling issue with `<label>` related to the new upgrade-alert notice. 
before: https://www.chapman.edu/website-feedback-form.aspx
after: https://dev-www.chapman.edu/website-feedback-form.aspx

move leftover CSS causing global <label> conflicts

---

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl

story: https://trello.com/c/wwpYthB8
before: https://www.chapman.edu/
after: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-6-2019/wave-upgrade-alert-empty-form.aspx

resolves Wave's "X Empty form label"

---

app/assets/stylesheets/components/google_search_v3_deprecated_default.scss

GET request to the Google Search stylesheet at https://www.google.com/cse/static/style/look/v3/deprecated_default.css is 404ing, so I've temporarily grabbed a copy from https://web.archive.org/web/20190525144154/https://www.chapman.edu/
before:  https://dev-www.chapman.edu/about/index.aspx
after: https://dev-www.chapman.edu/
I also have an inline hotfix in cascade-assets.xml on https://www.chapman.edu/ (only homepage has been published) 
spawned: https://trello.com/c/PxvDekke

add cached copy of 404ing stylesheet

---

app/assets/stylesheets/themes/communication.scss

Follow-up to https://github.com/chapmanu/cascade-assets/pull/487
(I'd missed the custom social PNGs on Comm's two column pages)
before: https://www.chapman.edu/communication/about.aspx
after: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-6-2019/communication/about.aspx

changes social icons to default on communication/about

---

app/assets/javascripts/widgets/image_slider.js
app/assets/stylesheets/widgets/single_column/call_to_action_3_up.scss
app/assets/stylesheets/widgets/single_column/image_slider.scss

Followup to #496 where I'd committed unintentional files. 
story: https://trello.com/c/tSTrMk5B
Note: I was unable to replicate `On the text with image widget, at the bottom transition to the next widget, I get this happening often with the overlap` on existing `before` page or dev `after` page
before: https://www.chapman.edu/industry-partners/index.aspx
after: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-19-2019/image-slider-no-padding.aspx

Defect - one col widgets

---

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/call_to_action_3_up.vtl
.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/image_slider_widget.vtl
app/assets/javascripts/widgets/image_slider.js
app/assets/stylesheets/widgets/single_column/call_to_action_3_up.scss
app/assets/stylesheets/widgets/single_column/image_slider.scss
app/views/widgets/single_column/_call_to_action_3_up.html

Ross noticed a few lingering issues on https://www.chapman.edu/industry-partners/index.aspx, namely:
- spacing below the CTA 3-up headings
- some height issues on the image slider which I discovered were related to the WYSWIYG adding empty `<p>` tags / additional rich text formatting depending on how content was pasted. 
- removed text-truncating on the Image Slider velocity format
- Image Slider content area attempts to accommodate a large amount of text (instead of line-clamp)... even though web coordinators would likely prevent this scenario from occurring 
before: https://www.chapman.edu/industry-partners/index.aspx
after: https://dev-www.chapman.edu/test-section/nick-test/sprint-6-19-2019/industry-partners.aspx

Defect - 1col widgets

---

.cascade-code/Chapman.edu/_cascade/formats/level/Masthead.vtl

Mandy noticed I'd left an unused link target reference in Masthead.vtl, related to https://github.com/chapmanu/cascade-assets/pull/475/files#diff-20fd19a42072422f401b0ad55e64ea2f
demo: https://dev-cascade.chapman.edu/entity/open.act?id=8f89d8cfc0a81e4b2afe10e73a0e6b94&type=page

Remove unused linkTarget reference

---

app/assets/stylesheets/widgets/home_page/upgrade_alert.scss

Spike/story https://trello.com/c/YKuuU27o (comments and 'IE11 screenshot.jpg')
( Expected behavior is that the upgrade alert should not show at all on ie11 )
Demo: 
Browserstack: https://live.browserstack.com/dashboard#os=Windows&os_version=8.1&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fwww.chapman.edu%2F&speed=1&host_ports=google.com%2C80%2C0
Page: https://dev-www.chapman.edu/test-section/nick-test/sprint-5-8-19/upgrade-browser.aspx

Defect - ie11/upgrade alert partially showing

---

.cascade-code/Chapman.edu/_cascade/formats/modular/PrimaryContent.vtl
.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Html Block.vtl
app/data_definitions/from_cascade/three_column.xml
app/data_definitions/from_cascade/two_column.xml

new widget to allow embedding a block of html, iframe or javascript into a page in Cascade. Just a text box, not wysiwyg editor. Specifically created for Chris Bryant to put the emergency/rave feed into a page but can be used for other things too. Is for the 2 and 3 Column Modular templates. Allows the code to be entered manually, or to pull in a block stored in /blocks folder in Cascade. either way.

New Html Block widget

---

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Collapsibles.vtl
app/assets/stylesheets/widgets/primary_column/collapsibles.scss

The expand/collapse toggle will now display even if there is no 'intro copy' text
demo: https://dev-www.chapman.edu/test-section/nick-test/sprint-early-september-2019/collapsible-widget-expand-all-fix.aspx

restructure expand/collapse toggle 

---

app/assets/javascripts/cascade/faculty-directory/school-listing.js

Engineering moved their page again and the path is the trigger to indicate what faculty school/dept to filter for the page listing

fix path again for Engineering page to correct filter

---

.cascade-code/Chapman.edu/_cascade/formats/modular/LeftColumnContent.vtl
.cascade-code/Chapman.edu/_cascade/formats/modular/PrimaryContent.vtl
.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Featured_News_Events_Left_Col.vtl
.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/Featured_News_Events_Primary_Content.vtl
app/data_definitions/from_cascade/three_column.xml
app/data_definitions/from_cascade/two_column.xml

Some minor changes to the news/events widget for accessibility eg different text in the various View All links so different from each other; a placeholder image for Feature instead of empty src="". Also prevent the html for the widget from being placed on the page if user selected the widget but then elected Do Not Show as the dropdown option. That will prevent placeholder and empty html for things that aren't used anyway but flagged as issues with SiteImprove. Also add Academics as news widget feed option for Academic Technology blog.

Fixes to news events widget (fall 2019)

---

app/assets/javascripts/widgets/upgrade_alert.js
app/assets/stylesheets/components/upgrade-alert.scss

This still checks for CSS Grid based on https://caniuse.com/#feat=css-grid and https://www.chapman.edu/upgrade-browser.aspx. Just removes extra conditional Javascript that I'd added to only run if the browser didn't support grid. 
i: 11,
e: 15,
f: 52,
o: 44,
s: 10.1,
c: 57

ie 11 was broken with the previous js (checking for CSS grid support)

---

.cascade-code/Chapman.edu/_cascade/formats/omni_nav_v2.vtl
.cascade-code/Chapman.edu/_config/global_nav.vm
app/views/widgets/shared/_header.html

remove link that's currently in omniNav and hamburger's Main Menu in the Research section. It's the Graduate Research link. Per SMC that site is being retired.

remove link to Graduate Research in omniNav

---

app/assets/stylesheets/omni_nav/omni_nav_v2/off-canvas-nav.scss

I noticed an issue with the Omninav Breakpoint fix (https://github.com/chapmanu/cascade-assets/pull/555) where the off-canvas logo was tiny as a side effect:
https://dev-cascade.chapman.edu/entity/open.act?id=b6c55838c0a81e4b01e4ac41bb0f9bf7&type=page
This increases specificity to resolve the issue:
https://dev-cascade.chapman.edu/entity/open.act?id=23ff703ac0a81e4b53bc07db5269cb12&type=page
There is a hotfix on production

increase .logo-container specificity

---

app/assets/stylesheets/components/upgrade-alert.scss

The browser upgrade alert has a `<noscript>` fallback. I noticed it flashes briefly (on a page with working JavaScript) if the page isn't cached. This uses a CSS keyframe to apply a delayed fadeIn when JS is disabled/broken/hasn't loaded yet
https://dev-www.chapman.edu/test-section/nick-test/browser-upgrade-noscript-opacity.aspx (try with JS disabled)

add opacity and delay to noscript upgrade alert

---

.cascade-code/Chapman.edu/_cascade/formats/Homepage UG Admission Section
app/assets/javascripts/cascade/homepage.js
app/assets/javascripts/cascade/new-home.js
app/assets/javascripts/master.js
app/assets/stylesheets/widgets/home_page/undergraduate_admission.scss
app/views/widgets/home_page/_undergraduate_admission.html

https://trello.com/c/SlVv1TZX
I wanted to get your opinions to see if this is a reasonable/valid solution. If not, I'll remove the counter animation and add a Trello card until we have more bandwidth.
The issue seems to stem from the JavaScript occassionally changing the actual default `original_num` value.
I've added a `data-count` attribute to the velocity format, which takes the initial value of `$factNumber` and some JS to check if that attribute exists (since other pages seem to rely on the `animateSingleNumber` function and might not have `data-count`.  
for demo purposes, the velocity format's first fact text value is '666':
https://dev-www.chapman.edu/test-section/nick-test/homepage-big-stats-2.aspx/#undergraduateAdmission
update: added opacity on initial load after discussing …

Defect - homepage bigs stats widget

---

.cascade-code/Chapman.edu/_cascade/formats/modular/widgets/one_column/call_to_action_3_up.vtl
app/assets/stylesheets/widgets/single_column/call_to_action_3_up.scss
app/data_definitions/from_cascade/one_column.xml
app/views/1_column/hero_side_panel.html.erb
app/views/widgets/single_column/_call_to_action_3_up.html

A small change to 1 Col to add a section heading field similar to other widgets, this for the Call To Action 3 Up widget. Ross got request from Law School. Sample shown on https://dev-www.chapman.edu/law/index-test2.aspx

Add heading field to CTA 3-upwidget  in 1 Column  Modular

---

app/assets/javascripts/cascade/homepage.js
app/views/layouts/application.html.erb
app/views/layouts/cascade-assets.xml.erb
app/views/uninav/three_column.html.erb
app/views/uninav/two_column.html.erb

Followup to #625, which prevented 2 & 3 Column Masthead images from loading: https://recordit.co/NhJmbwODis
I believe the function at **line 312** `var requested_story_slug` in `homepage.js` is needed in some capacity. Restoring it seems to resolve the issue: https://dev-cascade.chapman.edu/entity/open.act?id=f6c71415c04d744c54334eca0fd48b25&type=page

Tecknicks - previous PR broke 2, 3 col mastheads
